spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: roy07042001
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080